### ISSUE TITLE
Fails to open IfcOpenHouse

### ISSUE THREAD

**Issue by pablo-mayrgundter** [yorikvanhavre/FreeCAD-NativeIFC#18]
```shell
OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: (HEAD detached at 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.10.8, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * FreeCAD-NativeIFC 2022.10.20
```

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/2480879/212320436-94ac83ad-bdf7-4a0b-89c5-e9eae7ff2abe.png">

**Comment by yorikvanhavre** [comment]
Thanks for the notification!
I'm actually reworking all that part to suppress the Mesh version (the Shape-based version will now be able to only display the coin mesh instead of the full shape). Hopefully it will make this issue disappear. I'll comment back here when it's done so you can test...

**Comment by yorikvanhavre** [comment]
As far as I can see this is now solved after 22ab0e6. Please test again, and reopen this if needed!

**Comment by pablo-mayrgundter** [comment]
Hi, sorry slow on this!  I didn't realize there was auto-update of the plugin within FreeCAD.. that's nice and easy and will do that next time

Still not working for me on IfcOpenHouse, or even on our very simple project logo (similar with haus.ifc and window.ifc in this repo directory.):
  https://github.com/bldrs-ai/Share/blob/main/public/index.ifc

I'm seeing more progress now: FreeCAD shows the spatial hierarchy, and properties of a selected element, but no geometry and a long stack trace in the reports window.  But still not seeing geometry come thru, Initial load time is also way faster!  But curious to see it get through to 3d model.

Expected geometry (live in bldrs):
  https://bldrs.ai/share/v/p/index.ifc/89/112/139/154/546#c:-111.37,14.94,90.63,-43.48,15.73,-4.34
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/2480879/220210330-29d734bb-2a9e-40dc-894d-29e6008b712c.png">

NativeIFC loader with a failure: "<class 'TypeError'>: cannot create 'N4Base19ProgressIndicatorPyE' instances":
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/2480879/220208900-b3affcdd-cf7e-47bb-be4e-4732b19fc401.png">

Here's my import options:
<img width="337" alt="image" src="https://user-images.githubusercontent.com/2480879/220209457-7ee78ff7-fd9d-4d4c-b70f-a001d236b473.png">

And version info:
<img width="730" alt="image" src="https://user-images.githubusercontent.com/2480879/220209509-12cb3aed-1422-4757-9058-d7e5389223fa.png">

**Comment by berndhahnebach** [comment]
no problems here ... with file from here https://github.com/aothms/IfcOpenHouse/blob/master/IfcOpenHouse_IFC2x3.ifc

![screen1](https://user-images.githubusercontent.com/6129869/220689020-8c4bbcef-defa-4618-90da-aaaaadf433e5.png)

**Comment by pablo-mayrgundter** [comment]
Ah interesting.. you're on FreeCAD 0.21.0.. I'm on 0.20.2, the most recent release from FreeCAD site for OSX.

Do you think that's it?
